Лабораторная работа №4
Programming-Classrooms/practicalworks-KonstantinVrunouski pull request #4
Opened 2023-12-03 19:01 UTC by KonstantinVrunouski

## Pull Request лабораторной работы №4

### Условие лабраторной работы

Вариант 1
В целочисленной квадратной матрице найти:
- максимальный элемент в тех столбцах, которые не содержат положительных
элементов;
- подсчитать количество отрицательных элементов в нижнем правом
треугольнике квадратной матрицы, включая диагональ.

2023-12-12 15:46 UTC, AnnaSatolina requested changes
Можешь лучше и правильнее...переделать, Костя

2023-12-12 15:46 UTC, AnnaSatolina commented on laboratory-task-4/main.cpp
> +	if (max == INT32_MIN)
а если это реально и есть ответ задачи. Такое же тоже может быть

2023-12-12 15:46 UTC, AnnaSatolina commented on laboratory-task-4/main.cpp
> +}
если первая не решается, те исключение типа все элементы матрицы положительные числа, то и вторая не решается. Это учитывается?

2023-12-12 15:46 UTC, AnnaSatolina commented on laboratory-task-4/main.cpp
> +			fill_mtrx_man(mtrx, size);
не хватает фигурных скобок

2023-12-12 15:46 UTC, AnnaSatolina commented on laboratory-task-4/main.cpp
> +		int32_t max = max_el_col(mtrx, size);
Почему один такой элемент, если нужно найти максимальный элемент **в тех столбцах,** которые не содержат положительных элементов;

2023-12-12 15:46 UTC, AnnaSatolina commented on laboratory-task-4/main.cpp
> +	catch (std::exception e)
сложные типы передаются по ссылке или через указатель

2023-12-12 15:46 UTC, AnnaSatolina commented on laboratory-task-4/main.cpp
> +	size_t k = 0, cnt = 0;
честно, из названий непонятно за что отвечает л, а за что cnt

2023-12-12 15:46 UTC, AnnaSatolina commented on laboratory-task-4/main.cpp
> +}
а как же обработка исключений?

2023-12-24 19:12 UTC, KonstantinVrunouski commented on laboratory-task-4/main.cpp
> +		int32_t max = max_el_col(mtrx, size);
Находится один элемент из всех столбцов, удовлетворяющих условию.

2023-12-24 19:15 UTC, KonstantinVrunouski commented on laboratory-task-4/main.cpp
> +}
Первая задача может не решаться не только в этом случае. Также она не решится если в каждом столбце всего лишь один положительный элемент, находящийся вне нижнего правого треугольника.

2023-12-24 19:19 UTC, KonstantinVrunouski commented on laboratory-task-4/main.cpp
> +}
В данном случае передо мной стоял выбор между читаемостью кода и его производительностью. Учитывая образовательный характер данной программы (а конкретно работу с небольшим количеством данных) я выбрал в пользу читаемости, но в тоже время не забыв про возможность улучшения производительности в случае острой необходимости.

2024-06-17 16:21 UTC, AlexandrOsiptsov approved these changes
Финальный авто-апрув

2024-06-17 16:40 UTC, merged